cs:
    languageName: Czechi
    languageCode: cs
    weight: 1
    menus:
        main:
            - name: Tišnovská padesátka
              pageRef: /padesatka
              weight: 1
            - name: Příspěvky
              pageRef: /posts
              weight: 2
            - name: Kontakt
              pageRef: /about
              weight: 3
