cs:
    label: Czechi
    locale: cs
    weight: 1
    menus:
        main:
            - name: Tišnovská padesátka
              pageRef: /padesatka
              weight: 2
            - name: Archiv výletů
              pageRef: /vylety
              weight: 3
            - name: Ze života klubu
              pageRef: /posts
              weight: 4
            - name: O nás a členství
              pageRef: /about
              weight: 5
            - name: Kontakt
              pageRef: /about/kontakt
              weight: 6
